<concept_spec>
```
concept ProgressionBuilder

purpose 
    help users find harmonious chords quickly

principle
    the user sets the key of the progression, can add or delete chords from progression, and receives suggestions for chords at any specified position in the progression from an LLM given the context of the chord.

state
    a progression Progression with
        a key String, the musical key of the progression
        a sequence of chords Chord, each with a string corresponding with a musical chord or null to represent no chord has been selected for this slot

actions
    setKey(progression, key):
        effect sets the key of progression to key

    addSlot(position: Number):
        requires position is a valid index of Chords or position is undefined
        effect if position is undefined, adds a null chord at the end of the progression; otherwise, adds a null chord at the given position in the progression
    
    addChord(position: Number, chord: String):
        requires position is a valid index of Chords
        effect sets the chord at the given position to the given chord
    
    removeSlot(position: Number):
        requires position is a valid index of Chords
        effect removes the chord at the given position

    removeChord(position: Number):
        requires position is a valid index of Chords
        effect sets chord to null at the given position

    suggestChords(progression, position: Number): (list of chords)
        requires position is a valid index of Chords
        effect returns a list of suggested chords to put in position of the Chords, generated by an LLM given the context of the chord.
```
</concept_spec>